import fs from 'fs';
import path from 'path';

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const originalHEYS = window.HEYS;

function loadTrialQueueModule() {
    const modulePath = path.resolve(__dirname, '../heys_trial_queue_v1.js');
    eval(fs.readFileSync(modulePath, 'utf8'));
}

describe('HEYS.TrialQueue.admin Telegram recovery', () => {
    let rpc;

    beforeEach(() => {
        rpc = vi.fn();
        window.localStorage.clear();
        window.HEYS = { YandexAPI: { rpc } };
        loadTrialQueueModule();
    });

    afterEach(() => {
        vi.restoreAllMocks();
        window.localStorage.clear();
        window.HEYS = originalHEYS;
    });

    it('clearTelegramBinding calls curator RPC with client id and unwraps function payload', async () => {
        rpc.mockResolvedValue({
            data: {
                admin_clear_telegram_binding: {
                    success: true,
                    client_id: 'client-1',
                    cleared: true,
                },
            },
            error: null,
        });

        const result = await window.HEYS.TrialQueue.admin.clearTelegramBinding('client-1');

        expect(result).toEqual({
            success: true,
            client_id: 'client-1',
            cleared: true,
        });
        expect(rpc).toHaveBeenCalledWith('admin_clear_telegram_binding', {
            p_client_id: 'client-1',
        });
    });

    it('regeneratePin calls curator RPC and returns one-time access data', async () => {
        rpc.mockResolvedValue({
            data: {
                admin_regenerate_pin: {
                    success: true,
                    client_id: 'client-1',
                    pin: '4016',
                    pin_token: '11111111-1111-4111-8111-111111111111',
                    sessions_revoked: 2,
                    telegram_binding_cleared: true,
                },
            },
            error: null,
        });

        const result = await window.HEYS.TrialQueue.admin.regeneratePin('client-1');

        expect(result.success).toBe(true);
        expect(result.pin).toBe('4016');
        expect(result.pin_token).toBe('11111111-1111-4111-8111-111111111111');
        expect(result.sessions_revoked).toBe(2);
        expect(rpc).toHaveBeenCalledWith('admin_regenerate_pin', {
            p_client_id: 'client-1',
        });
    });

    it('getClientAccessLink calls curator RPC and unwraps current link payload', async () => {
        rpc.mockResolvedValue({
            data: {
                admin_get_client_access_link: {
                    success: true,
                    client_id: 'client-1',
                    link_available: true,
                    pin_token: '11111111-1111-4111-8111-111111111111',
                    pin_token_expires_at: '2026-06-23T00:00:00.000Z',
                    deep_link: 'https://t.me/heyslab_bot?start=11111111-1111-4111-8111-111111111111',
                },
            },
            error: null,
        });

        const result = await window.HEYS.TrialQueue.admin.getClientAccessLink('client-1');

        expect(result.success).toBe(true);
        expect(result.link_available).toBe(true);
        expect(result.deep_link).toBe('https://t.me/heyslab_bot?start=11111111-1111-4111-8111-111111111111');
        expect(rpc).toHaveBeenCalledWith('admin_get_client_access_link', {
            p_client_id: 'client-1',
        });
    });

    it('getClientAccessLink keeps expired token response explicit for UI', async () => {
        rpc.mockResolvedValue({
            data: {
                admin_get_client_access_link: {
                    success: true,
                    client_id: 'client-1',
                    link_available: false,
                    reason: 'token_expired',
                    message: 'Telegram-ссылка истекла. Перевыпустите PIN и ссылку.',
                },
            },
            error: null,
        });

        const result = await window.HEYS.TrialQueue.admin.getClientAccessLink('client-1');

        expect(result).toMatchObject({
            success: true,
            link_available: false,
            reason: 'token_expired',
        });
    });

    it('maps RPC errors to admin error shape', async () => {
        rpc.mockResolvedValue({
            data: null,
            error: { code: 'forbidden', message: 'Forbidden' },
        });

        const result = await window.HEYS.TrialQueue.admin.clearTelegramBinding('client-1');

        expect(result).toEqual({
            success: false,
            error: 'forbidden',
            message: 'Forbidden',
        });
    });

    it('convertLead sends only lead id because PIN is generated by SQL', async () => {
        rpc.mockResolvedValue({
            data: {
                admin_convert_lead: {
                    success: true,
                    client_id: 'client-1',
                    pin: '4016',
                    pin_token: '11111111-1111-4111-8111-111111111111',
                },
            },
            error: null,
        });

        const result = await window.HEYS.TrialQueue.admin.convertLead('lead-1');

        expect(result.success).toBe(true);
        expect(result.pin).toBe('4016');
        expect(rpc).toHaveBeenCalledWith('admin_convert_lead', {
            p_lead_id: 'lead-1',
        });
    });
});
