// heys_app_shell_props_v1.js — AppShell props builder

(function () {
    const HEYS = window.HEYS = window.HEYS || {};
    HEYS.AppShellProps = HEYS.AppShellProps || {};

    HEYS.AppShellProps.buildAppShellProps = function ({
        isConsentBlocking,
        isMorningCheckinBlocking,
        clientId,
        tab,
        setTab,
        selectedDate,
        setSelectedDate,
        todayISO,
        datePickerActiveDays,
        products,
        setProducts,
        cachedProfile,
        currentClientName,
        getAvatarColor,
        getClientInitials,
        getClientStats,
        formatLastActive,
        clients,
        setClientId,
        showClientDropdown,
        setShowClientDropdown,
        isRpcMode,
        cloudUser,
        handleSignOut,
        U,
        cloudStatus,
        syncProgress,
        pendingCount,
        pendingDetails,
        pendingText,
        pendingActionItems,
        showPendingSyncBanner,
        retryCountdown,
        GamificationBar,
        widgetsEditMode,
        defaultTab,
        setDefaultTab,
        slideDirection,
        edgeBounce,
        onTouchStart,
        onTouchEnd,
        syncVer,
        DayTabWithCloudSync,
        RationTabWithCloudSync,
        UserTabWithCloudSync,
    }) {
        return {
            // 🔧 v69: Force remount of AppShell on client switch.
            // Иначе внутренние useState/useMemo в DayTab/AppHeader могут на один кадр
            // показать данные предыдущего клиента до того, как hydration дочитает новый localStorage.
            key: 'app-shell-' + (clientId || 'none'),
            hideContent: (isConsentBlocking || isMorningCheckinBlocking || !clientId),
            clientId,
            clientIdValue: clientId,
            tab,
            setTab,
            selectedDate,
            setSelectedDate,
            todayISO,
            datePickerActiveDays,
            products,
            setProducts,
            cachedProfile,
            currentClientName,
            getAvatarColor,
            getClientInitials,
            getClientStats,
            formatLastActive,
            clients,
            setClientId,
            showClientDropdown,
            setShowClientDropdown,
            isRpcMode,
            cloudUser,
            handleSignOut,
            U,
            cloudStatus,
            syncProgress,
            pendingCount,
            pendingDetails,
            pendingText,
            pendingActionItems,
            showPendingSyncBanner,
            retryCountdown,
            GamificationBar,
            widgetsEditMode,
            defaultTab,
            setDefaultTab,
            slideDirection,
            edgeBounce,
            onTouchStart,
            onTouchEnd,
            syncVer,
            DayTabWithCloudSync,
            RationTabWithCloudSync,
            UserTabWithCloudSync,
        };
    };
})();
