// heys_day_tab_render_v1.js — DayTab render assembly (read-only/diary/shell)

; (function (global) {
    const HEYS = global.HEYS = global.HEYS || {};

    HEYS.dayTabRender = HEYS.dayTabRender || {};

    HEYS.dayTabRender.renderDayTabLayout = function renderDayTabLayout(ctx) {
        const React = ctx.React || global.React;
        const heysRef = ctx.HEYS || HEYS;

        // === READ-ONLY BANNER: показываем только для подтверждённого read_only ===
        const subscriptionStatus = heysRef.Subscription?.getCachedStatus?.() || ctx.prof?.subscription_status || 'none';
        const normalizedSubscriptionStatus = heysRef.Subscription?.normalizeStatus?.(subscriptionStatus) || subscriptionStatus;
        const isReadOnly = normalizedSubscriptionStatus === 'read_only';

        // === Diary Section (extracted) ===
        // Heavy diary mounts after first paint; until then the boot-mark stays.
        const diarySection = ctx.heavyUiReady
            ? (heysRef.dayDiarySection?.renderDiarySection?.({
                React,
                isMobile: ctx.isMobile,
                mobileSubTab: ctx.mobileSubTab,
                goalProgressBar: ctx.goalProgressBar,
                mealsChart: ctx.mealsChart,
                insulinWaveData: ctx.insulinWaveData,
                insulinExpanded: ctx.insulinExpanded,
                setInsulinExpanded: ctx.setInsulinExpanded,
                openExclusivePopup: ctx.openExclusivePopup,
                addMeal: ctx.addMeal,
                day: ctx.day,
                mealsUI: ctx.mealsUI,
                dailyWaveOverview: ctx.dailyWaveOverview,
                daySummary: ctx.daySummary,
                caloricDebt: ctx.caloricDebt,
                eatenKcal: ctx.eatenKcal,
                optimum: ctx.optimum,
                displayOptimum: ctx.displayOptimum,
                date: ctx.date,
                prof: ctx.prof,
                pIndex: ctx.pIndex,
                dayTot: ctx.dayTot,
                normAbs: ctx.normAbs,
                HEYS: heysRef
            }) || null)
            : null;

        if (!heysRef.dayPageShell?.renderDayPage) {
            throw new Error('[heys_day_tab_render_v1] HEYS.dayPageShell not loaded before renderDayTabLayout');
        }

        const adviceState = ctx.adviceState || {};

        return heysRef.dayPageShell.renderDayPage({
            isReadOnly,
            pullProgress: ctx.pullProgress,
            isRefreshing: ctx.isRefreshing,
            refreshStatus: ctx.refreshStatus,
            pullThreshold: ctx.pullThreshold,
            isMobile: ctx.isMobile,
            mobileSubTab: ctx.mobileSubTab,
            isTabActive: ctx.isTabActive !== false,
            orphanAlert: ctx.orphanAlert,
            lowCalBanner: ctx.lowCalBanner,
            statsBlock: ctx.statsBlock,
            compactActivity: ctx.compactActivity,
            compactNutrition: ctx.compactNutrition,
            sideBlock: ctx.sideBlock,
            cycleCard: ctx.cycleCard,
            reportsOverviewCard: ctx.reportsOverviewCard,
            reportsFullscreenModal: ctx.reportsFullscreenModal,
            date: ctx.date,
            day: ctx.day,
            caloricDebt: ctx.caloricDebt,
            eatenKcal: ctx.eatenKcal,
            optimum: ctx.optimum,
            displayOptimum: ctx.displayOptimum,
            tdee: ctx.tdee,
            addMeal: ctx.addMeal,
            addWater: ctx.addWater,
            removeWater: ctx.removeWater,
            diarySection,
            adviceTrigger: adviceState.adviceTrigger,
            adviceRelevant: adviceState.adviceRelevant,
            badgeAdvices: adviceState.badgeAdvices,
            totalAdviceCount: adviceState.totalAdviceCount,
            toastVisible: adviceState.toastVisible,
            dismissToast: adviceState.dismissToast,
            getSortedGroupedAdvices: adviceState.getSortedGroupedAdvices,
            dismissedAdvices: adviceState.dismissedAdvices,
            hiddenUntilTomorrow: adviceState.hiddenUntilTomorrow,
            lastDismissedAdvice: adviceState.lastDismissedAdvice,
            adviceSwipeState: adviceState.adviceSwipeState,
            expandedAdviceId: adviceState.expandedAdviceId,
            handleAdviceToggleExpand: adviceState.handleAdviceToggleExpand,
            trackClick: adviceState.trackClick,
            rateAdvice: adviceState.rateAdvice,
            handleAdviceSwipeStart: adviceState.handleAdviceSwipeStart,
            handleAdviceSwipeMove: adviceState.handleAdviceSwipeMove,
            handleAdviceSwipeEnd: adviceState.handleAdviceSwipeEnd,
            handleAdviceLongPressStart: adviceState.handleAdviceLongPressStart,
            handleAdviceLongPressEnd: adviceState.handleAdviceLongPressEnd,
            registerAdviceCardRef: adviceState.registerAdviceCardRef,
            handleAdviceListTouchStart: adviceState.handleAdviceListTouchStart,
            handleAdviceListTouchMove: adviceState.handleAdviceListTouchMove,
            handleAdviceListTouchEnd: adviceState.handleAdviceListTouchEnd,
            handleDismissAll: adviceState.handleDismissAll,
            dismissAllAnimation: adviceState.dismissAllAnimation,
            toastsEnabled: adviceState.toastsEnabled,
            toggleToastsEnabled: adviceState.toggleToastsEnabled,
            adviceSoundEnabled: adviceState.adviceSoundEnabled,
            toggleAdviceSoundEnabled: adviceState.toggleAdviceSoundEnabled,
            scheduleAdvice: adviceState.scheduleAdvice,
            undoLastDismiss: adviceState.undoLastDismiss,
            clearLastDismissed: adviceState.clearLastDismissed,
            undoCountdownSeconds: adviceState.undoCountdownSeconds,
            adviceServiceOpen: adviceState.adviceServiceOpen,
            openAdviceService: adviceState.openAdviceService,
            closeAdviceService: adviceState.closeAdviceService,
            openAdviceRulesPool: adviceState.openAdviceRulesPool,
            closeAdviceRulesPool: adviceState.closeAdviceRulesPool,
            adviceRulesPoolOpen: adviceState.adviceRulesPoolOpen,
            retryAdviceMarksSync: adviceState.retryAdviceMarksSync,
            copyAdviceTrace: adviceState.copyAdviceTrace,
            adviceTraceAvailable: adviceState.adviceTraceAvailable,
            adviceTraceCopyState: adviceState.adviceTraceCopyState,
            adviceDiagnostics: adviceState.adviceDiagnostics,
            adviceDiagnosticsOpen: adviceState.adviceDiagnosticsOpen,
            openAdviceDiagnostics: adviceState.openAdviceDiagnostics,
            closeAdviceDiagnostics: adviceState.closeAdviceDiagnostics,
            adviceDetailModalOpen: adviceState.adviceDetailModalOpen,
            adviceDetailModalAdvice: adviceState.adviceDetailModalAdvice,
            openAdviceDetailModal: adviceState.openAdviceDetailModal,
            closeAdviceDetailModal: adviceState.closeAdviceDetailModal,
            markAdviceDetailRead: adviceState.markAdviceDetailRead,
            hideAdviceDetailUntilTomorrow: adviceState.hideAdviceDetailUntilTomorrow,
            adviceTechnicalDetails: adviceState.adviceTechnicalDetails,
            adviceTechnicalDetailsOpen: adviceState.adviceTechnicalDetailsOpen,
            openAdviceTechnicalDetails: adviceState.openAdviceTechnicalDetails,
            closeAdviceTechnicalDetails: adviceState.closeAdviceTechnicalDetails,
            ADVICE_CATEGORY_NAMES: adviceState.ADVICE_CATEGORY_NAMES,
            ewsWarnings: adviceState.ewsWarnings,
            AdviceCard: ctx.AdviceCard,
            adviceSettingsOpen: adviceState.adviceSettingsOpen,
            closeAdviceSettings: adviceState.closeAdviceSettings,
            adviceCategorySettings: adviceState.adviceCategorySettings,
            toggleAdviceCategoryGroup: adviceState.toggleAdviceCategoryGroup,
            medicalDisclaimerSessionDismissed: adviceState.medicalDisclaimerSessionDismissed,
            medicalDisclaimerNeverShow: adviceState.medicalDisclaimerNeverShow,
            setMedicalDisclaimerNeverShow: adviceState.setMedicalDisclaimerNeverShow,
            dismissMedicalDisclaimerGate: adviceState.dismissMedicalDisclaimerGate,
            displayedAdvice: adviceState.displayedAdvice,
            toastSwiped: adviceState.toastSwiped,
            toastSwipeX: adviceState.toastSwipeX,
            toastRatedState: adviceState.toastRatedState,
            dismissToast: adviceState.dismissToast,
            handleToastRate: adviceState.handleToastRate,
            handleToastTouchStart: adviceState.handleToastTouchStart,
            handleToastTouchMove: adviceState.handleToastTouchMove,
            handleToastTouchEnd: adviceState.handleToastTouchEnd,
            openAdviceDetailModal: adviceState.openAdviceDetailModal,
            adviceTechnicalDetails: adviceState.adviceTechnicalDetails,
            adviceTechnicalDetailsOpen: adviceState.adviceTechnicalDetailsOpen,
            closeAdviceTechnicalDetails: adviceState.closeAdviceTechnicalDetails,
            showTimePicker: ctx.showTimePicker,
            cancelTimePicker: ctx.cancelTimePicker,
            bottomSheetRef: ctx.bottomSheetRef,
            handleSheetTouchStart: ctx.handleSheetTouchStart,
            handleSheetTouchMove: ctx.handleSheetTouchMove,
            handleSheetTouchEnd: ctx.handleSheetTouchEnd,
            pickerStep: ctx.pickerStep,
            animDirection: ctx.animDirection,
            editMode: ctx.editMode,
            confirmTimeEdit: ctx.confirmTimeEdit,
            goToMoodStep: ctx.goToMoodStep,
            hoursValues: ctx.hoursValues,
            pendingMealTime: ctx.pendingMealTime,
            setPendingMealTime: ctx.setPendingMealTime,
            minutesValues: ctx.minutesValues,
            isNightHourSelected: ctx.isNightHourSelected,
            currentDateLabel: ctx.currentDateLabel,
            pendingMealType: ctx.pendingMealType,
            setPendingMealType: ctx.setPendingMealType,
            WheelColumn: ctx.WheelColumn,
            goBackToTimeStep: ctx.goBackToTimeStep,
            confirmMoodEdit: ctx.confirmMoodEdit,
            confirmMealCreation: ctx.confirmMealCreation,
            pendingMealMood: ctx.pendingMealMood,
            setPendingMealMood: ctx.setPendingMealMood,
            showConfetti: ctx.showConfetti,
            setShowConfetti: ctx.setShowConfetti,
            emojiAnimating: ctx.emojiAnimating,
            setEmojiAnimating: ctx.setEmojiAnimating,
            prof: ctx.prof,
            pIndex: ctx.pIndex,
            lsGet: ctx.lsGet,
            fmtDate: ctx.fmtDate,
            getProductFromItem: ctx.getProductFromItem,
            getMealType: ctx.getMealType,
            getMealQualityScore: ctx.getMealQualityScore,
            editGramsTarget: ctx.editGramsTarget,
            editGramsValue: ctx.editGramsValue,
            editPortions: ctx.editPortions,
            editLastPortionGrams: ctx.editLastPortionGrams,
            editGramsInputRef: ctx.editGramsInputRef,
            setEditGramsValue: ctx.setEditGramsValue,
            confirmEditGramsModal: ctx.confirmEditGramsModal,
            cancelEditGramsModal: ctx.cancelEditGramsModal,
            handleEditGramsDrag: ctx.handleEditGramsDrag,
            zoneFormulaPopup: ctx.zoneFormulaPopup,
            closeZoneFormula: ctx.closeZoneFormula,
            householdFormulaPopup: ctx.householdFormulaPopup,
            closeHouseholdFormula: ctx.closeHouseholdFormula,
            showZonePicker: ctx.showZonePicker,
            cancelZonePicker: ctx.cancelZonePicker,
            confirmZonePicker: ctx.confirmZonePicker,
            zonePickerTarget: ctx.zonePickerTarget,
            zoneMinutesValues: ctx.zoneMinutesValues,
            pendingZoneMinutes: ctx.pendingZoneMinutes,
            setPendingZoneMinutes: ctx.setPendingZoneMinutes,
            showTrainingPicker: ctx.showTrainingPicker,
            cancelTrainingPicker: ctx.cancelTrainingPicker,
            confirmTrainingPicker: ctx.confirmTrainingPicker,
            trainingPickerStep: ctx.trainingPickerStep,
            pendingTrainingZones: ctx.pendingTrainingZones,
            setPendingTrainingZones: ctx.setPendingTrainingZones,
            pendingTrainingTime: ctx.pendingTrainingTime,
            setPendingTrainingTime: ctx.setPendingTrainingTime,
            pendingTrainingType: ctx.pendingTrainingType,
            setPendingTrainingType: ctx.setPendingTrainingType,
            trainingTypes: ctx.trainingTypes,
            kcalMin: ctx.kcalMin,
            TR: ctx.TR,
            mets: ctx.mets,
            zoneNames: ctx.zoneNames,
            weight: ctx.weight,
            kcalPerMin: ctx.kcalPerMin,
            r0: ctx.r0,
            householdActivities: ctx.householdActivities,
            openTrainingPicker: ctx.openTrainingPicker,
            openHouseholdPicker: ctx.openHouseholdPicker,
            pendingTrainingQuality: ctx.pendingTrainingQuality,
            setPendingTrainingQuality: ctx.setPendingTrainingQuality,
            pendingTrainingFeelAfter: ctx.pendingTrainingFeelAfter,
            setPendingTrainingFeelAfter: ctx.setPendingTrainingFeelAfter,
            pendingTrainingComment: ctx.pendingTrainingComment,
            setPendingTrainingComment: ctx.setPendingTrainingComment,
            showSleepQualityPicker: ctx.showSleepQualityPicker,
            cancelSleepQualityPicker: ctx.cancelSleepQualityPicker,
            confirmSleepQualityPicker: ctx.confirmSleepQualityPicker,
            pendingSleepQuality: ctx.pendingSleepQuality,
            setPendingSleepQuality: ctx.setPendingSleepQuality,
            pendingSleepNote: ctx.pendingSleepNote,
            setPendingSleepNote: ctx.setPendingSleepNote,
            sleepQualityValues: ctx.sleepQualityValues,
            showDayScorePicker: ctx.showDayScorePicker,
            cancelDayScorePicker: ctx.cancelDayScorePicker,
            confirmDayScorePicker: ctx.confirmDayScorePicker,
            pendingDayScore: ctx.pendingDayScore,
            setPendingDayScore: ctx.setPendingDayScore,
            pendingDayComment: ctx.pendingDayComment,
            setPendingDayComment: ctx.setPendingDayComment,
            calculateDayAverages: ctx.calculateDayAverages,
            mealQualityPopup: ctx.mealQualityPopup,
            setMealQualityPopup: ctx.setMealQualityPopup,
            getSmartPopupPosition: ctx.getSmartPopupPosition,
            createSwipeHandlers: ctx.createSwipeHandlers,
            M: ctx.M
        });
    };
})(window);
