import { canonicalJson, fnv1a64 } from './rng.js';
import { POLICY_IDS } from './policies.js';
import { registries } from './content/scenario.js';
import { CONTRACT, type CampaignResult, type PolicyId } from './types.js';
import type { QaRawCounts, QaReport } from './qa.js';

const sumRecord = (records: Array<Record<string, number>>): Record<string, number> => { const result:Record<string,number>={};for(const record of records)for(const [key,value] of Object.entries(record))result[key]=(result[key]??0)+value;return result; };
const zeroOutcomes=():CampaignResult['outcomes']=>({money:0,work:0,family:0,recovery:0,sleep:0});
const gate=(threshold:string,actual:number,passed:boolean)=>({threshold,actual,passed});

export function mergeCausalQaReports(input:QaReport[],createdAt=new Date().toISOString()):QaReport {
  if(!input.length)throw new Error('At least one QA shard is required');
  const reports=[...input].sort((a,b)=>a.simulation.seedStart-b.simulation.seedStart),first=reports[0]!;
  for(const report of reports)if(report.sourceFingerprint!==first.sourceFingerprint||canonicalJson(report.simulation.contracts)!==canonicalJson(first.simulation.contracts))throw new Error('QA shards use different source/contracts');
  let expectedStart=reports[0]!.simulation.seedStart;for(const report of reports){if(report.simulation.seedStart!==expectedStart)throw new Error(`QA shard gap/overlap at ${expectedStart}`);expectedStart+=report.simulation.seedCount;}
  const sum=(key:keyof QaRawCounts)=>reports.reduce((total,report)=>total+report.simulation.rawCounts[key],0),max=(key:keyof QaRawCounts)=>Math.max(...reports.map((report)=>report.simulation.rawCounts[key]));
  const rawCounts:QaRawCounts={terminal:sum('terminal'),ordinary:sum('ordinary'),ordinaryTwo:sum('ordinaryTwo'),hard:sum('hard'),hardSingle:sum('hardSingle'),heavy:sum('heavy'),stabilized:sum('stabilized'),multiStabilized:sum('multiStabilized'),maxExternal:max('maxExternal'),maxTotal:max('maxTotal'),maxLargeDay:max('maxLargeDay'),maxLargeWeek:max('maxLargeWeek'),boundarySteps:sum('boundarySteps'),totalSteps:sum('totalSteps'),auditedTransitions:sum('auditedTransitions'),unexplained:sum('unexplained'),personalization:sum('personalization')};
  const actionFrequency=sumRecord(reports.map((report)=>report.simulation.distributions.actionFrequency)),eventFrequency=sumRecord(reports.map((report)=>report.simulation.distributions.eventFrequency));
  const heavyWithoutStabilizerByEvent=sumRecord(reports.map((report)=>report.simulation.distributions.heavyWithoutStabilizerByEvent)),unexplainedPathFrequency=sumRecord(reports.map((report)=>report.simulation.distributions.unexplainedPathFrequency)),boundaryPathFrequency=sumRecord(reports.map((report)=>report.simulation.distributions.boundaryPathFrequency));
  const policyOutcomes=Object.fromEntries(POLICY_IDS.map((id)=>[id,zeroOutcomes()])) as Record<PolicyId,CampaignResult['outcomes']>;for(const report of reports)for(const policyId of POLICY_IDS)for(const key of Object.keys(policyOutcomes[policyId]) as Array<keyof CampaignResult['outcomes']>)policyOutcomes[policyId][key]+=report.simulation.distributions.policyOutcomes[policyId][key];
  const outcomeKeys=['money','work','family','recovery','sleep'] as const,policyGlobalDominanceCount=POLICY_IDS.filter((policy)=>POLICY_IDS.filter((other)=>other!==policy).every((other)=>outcomeKeys.every((key)=>policyOutcomes[policy][key]>=policyOutcomes[other][key])&&outcomeKeys.some((key)=>policyOutcomes[policy][key]>policyOutcomes[other][key]))).length;
  const counterfactuals=first.simulation.counterfactuals,auditedActionCount=Object.keys(actionFrequency).length,reproMismatchCount=reports.reduce((total,report)=>total+(report.simulation.metrics.reproMismatchCount??0),0);
  const echoIds=['thu_colleague_reciprocity','fri_final_issue_with_support','sat_meal_prep_familiar','sun_family_time_reciprocal'];
  const metrics={terminalLockCount:rawCounts.terminal,heavyStateStabilizationRate:rawCounts.heavy?rawCounts.stabilized/rawCounts.heavy:1,heavyMultiStabilizationRate:rawCounts.heavy?rawCounts.multiStabilized/rawCounts.heavy:1,ordinaryTwoChoiceRate:rawCounts.ordinary?rawCounts.ordinaryTwo/rawCounts.ordinary:1,hardSingleChoiceRate:rawCounts.hard?rawCounts.hardSingle/rawCounts.hard:0,actionDominanceRate:counterfactuals.reduce((sum,item)=>sum+item.dominantContextCount,0)/(counterfactuals.length*2),policyGlobalDominanceCount,largeExternalPerDayMax:rawCounts.maxLargeDay,largeExternalPerWeekMax:rawCounts.maxLargeWeek,externalLoadPerDayMax:rawCounts.maxExternal,totalEventLoadPerDayMax:rawCounts.maxTotal,boundaryStepRate:rawCounts.totalSteps?rawCounts.boundarySteps/rawCounts.totalSteps:0,unexplainedLongTermChangeCount:rawCounts.unexplained,reproMismatchCount,personalizationAdvantageCount:rawCounts.personalization,counterfactualPassRate:counterfactuals.filter((item)=>item.passed).length/counterfactuals.length,auditedActionCount,echoEventCoverageRate:echoIds.filter((id)=>eventFrequency[id]).length/echoIds.length};
  // `D74`: покрытие каталога перестало быть блокирующим gate. Оно измеряется и
  // попадает в отчёт, но при свободном порядке ситуаций одна выборка не обязана
  // показать весь контент; достижимость проверяет профиль `qa-profile.ts`.
  const gates={terminalLockCount:gate('=0',metrics.terminalLockCount,metrics.terminalLockCount===0),heavyStateStabilizationRate:gate('=1',metrics.heavyStateStabilizationRate,metrics.heavyStateStabilizationRate===1),heavyMultiStabilizationRate:gate('>=0.85',metrics.heavyMultiStabilizationRate,metrics.heavyMultiStabilizationRate>=.85),ordinaryTwoChoiceRate:gate('>=0.98',metrics.ordinaryTwoChoiceRate,metrics.ordinaryTwoChoiceRate>=.98),hardSingleChoiceRate:gate('<=0.02',metrics.hardSingleChoiceRate,metrics.hardSingleChoiceRate<=.02),actionDominanceRate:gate('<=0.70',metrics.actionDominanceRate,metrics.actionDominanceRate<=.70),policyGlobalDominanceCount:gate('=0',metrics.policyGlobalDominanceCount,metrics.policyGlobalDominanceCount===0),largeExternalPerDayMax:gate('<=1',metrics.largeExternalPerDayMax,metrics.largeExternalPerDayMax<=1),largeExternalPerWeekMax:gate('<=4',metrics.largeExternalPerWeekMax,metrics.largeExternalPerWeekMax<=4),externalLoadPerDayMax:gate('<=50',metrics.externalLoadPerDayMax,metrics.externalLoadPerDayMax<=50),totalEventLoadPerDayMax:gate('<=90',metrics.totalEventLoadPerDayMax,metrics.totalEventLoadPerDayMax<=90),boundaryStepRate:gate('<=0.20',metrics.boundaryStepRate,metrics.boundaryStepRate<=.20),unexplainedLongTermChangeCount:gate('=0',metrics.unexplainedLongTermChangeCount,metrics.unexplainedLongTermChangeCount===0),reproMismatchCount:gate('=0',metrics.reproMismatchCount,metrics.reproMismatchCount===0),personalizationAdvantageCount:gate('=0',metrics.personalizationAdvantageCount,metrics.personalizationAdvantageCount===0),counterfactualPassRate:gate('=1',metrics.counterfactualPassRate,metrics.counterfactualPassRate===1)};
  const missingSlots=first.simulation.coverage.missingSlots,missingEvents=Object.keys(registries.events).filter((id)=>!eventFrequency[id]),missingActions=Object.keys(registries.actions).filter((id)=>!actionFrequency[id]);
  const seedCount=reports.reduce((total,report)=>total+report.simulation.seedCount,0),runCount=reports.reduce((total,report)=>total+report.simulation.runCount,0),campaignSeedHashes=reports.flatMap((report)=>report.simulation.campaignSeedHashes),campaignHash=fnv1a64(campaignSeedHashes.join('\n')),failures=reports.flatMap((report)=>report.simulation.failures);
  const stablePayload={contracts:CONTRACT,sourceFingerprint:first.sourceFingerprint,seedCount,seedStart:reports[0]!.simulation.seedStart,policyIds:POLICY_IDS,runCount,replayVerificationCount:first.simulation.replayVerificationCount,campaignHash,campaignSeedHashes,rawCounts,metrics,gates,coverage:{slots:registries.slots.length-missingSlots.length,events:Object.keys(registries.events).length-missingEvents.length,actions:Object.keys(registries.actions).length-missingActions.length,missingSlots,missingEvents,missingActions},counterfactuals,distributions:{actionFrequency,eventFrequency,policyOutcomes,heavyWithoutStabilizerByEvent,unexplainedPathFrequency,boundaryPathFrequency,auditedTransitionCount:rawCounts.auditedTransitions,auditedActionCount},failures};
  return {reportVersion:2,createdAt,schemaVersion:2,scenarioId:CONTRACT.scenarioId,scenarioVersion:CONTRACT.scenarioVersion,calibrationVersion:CONTRACT.calibrationVersion,priceBookVersion:CONTRACT.priceBookVersion,rngAlgorithm:CONTRACT.rngAlgorithm,codeRevision:first.codeRevision,sourceFingerprint:first.sourceFingerprint,simulation:{...stablePayload,simulationHash:fnv1a64(canonicalJson(stablePayload))}};
}
