openapi: 3.0.0
info:
  title: HEYS API
  version: 1.2.0
  description: |
    HEYS Nutrition Tracker API (Yandex Cloud Functions)
    - Full API spec with all v1 endpoints + ЮKassa Payments preparation
    - /auth/clients endpoints merged from v1
    - Payments endpoints use health function as STUB until ЮKassa credentials received
    - Replace d4e0rqplbonspm84pk3n with real payments function ID when deployed

servers:
  - url: https://d5d7939njvjp27ofsok0.3zvepvee.apigw.yandexcloud.net
  - url: https://api.heyslab.ru
paths:
  # ═══════════════════════════════════════════════════════════════
  # RPC — PostgreSQL функции
  # ═══════════════════════════════════════════════════════════════
  /rpc:
    post:
      summary: PostgreSQL RPC calls
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e9e90es31bgjp87j8i
    options:
      summary: CORS preflight for RPC
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e9e90es31bgjp87j8i

  # ═══════════════════════════════════════════════════════════════
  # REST — CRUD операции с таблицами (query param: ?table=xxx)
  # ═══════════════════════════════════════════════════════════════
  /rest:
    get:
      summary: REST GET (SELECT) — ?table=xxx
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ea4j7eh05rtkjubipt
    post:
      summary: REST POST (INSERT)
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ea4j7eh05rtkjubipt
    patch:
      summary: REST PATCH (UPDATE)
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ea4j7eh05rtkjubipt
    delete:
      summary: REST DELETE
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ea4j7eh05rtkjubipt
    options:
      summary: CORS preflight for REST
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ea4j7eh05rtkjubipt

  # REST с path parameter (альтернативный путь)
  /rest/{table}:
    get:
      summary: REST GET (SELECT) — /rest/table_name
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ea4j7eh05rtkjubipt
    post:
      summary: REST POST (INSERT)
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ea4j7eh05rtkjubipt
    patch:
      summary: REST PATCH (UPDATE)
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ea4j7eh05rtkjubipt
    delete:
      summary: REST DELETE
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ea4j7eh05rtkjubipt
    options:
      summary: CORS preflight for REST with path
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ea4j7eh05rtkjubipt

  # ═══════════════════════════════════════════════════════════════
  # SMS — Отправка SMS через SMS.ru
  # ═══════════════════════════════════════════════════════════════
  /sms:
    post:
      summary: SMS sending via SMS.ru
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ejimndqnd8q72r9g00
    options:
      summary: CORS preflight for SMS
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ejimndqnd8q72r9g00

  # ═══════════════════════════════════════════════════════════════
  # Leads — Лиды с лендинга
  # ═══════════════════════════════════════════════════════════════
  /leads:
    post:
      summary: Landing page leads
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eml8vh341v41642cdu
    options:
      summary: CORS preflight for leads
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eml8vh341v41642cdu

  # ═══════════════════════════════════════════════════════════════
  # Health — Healthcheck
  # ═══════════════════════════════════════════════════════════════
  /health:
    get:
      summary: Healthcheck
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e0rqplbonspm84pk3n
    options:
      summary: CORS preflight for health
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e0rqplbonspm84pk3n

  # ═══════════════════════════════════════════════════════════════
  # Auth — Аутентификация кураторов (NEW!)
  # ═══════════════════════════════════════════════════════════════
  /auth/login:
    post:
      summary: Curator login (email + password)
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3
    options:
      summary: CORS preflight for auth login
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3

  /auth/verify:
    post:
      summary: Verify JWT token
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3
    options:
      summary: CORS preflight for auth verify
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3

  /auth/register:
    post:
      summary: Register new curator (admin only)
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3
    options:
      summary: CORS preflight for auth register
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3

  /auth/clients:
    get:
      summary: Get curator's clients list (requires JWT)
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3
    post:
      summary: Create new client (requires JWT)
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3
    options:
      summary: CORS preflight for auth clients
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3

  /auth/clients/{clientId}:
    patch:
      summary: Update client (requires JWT)
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3
    delete:
      summary: Delete client (requires JWT)
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3
    options:
      summary: CORS preflight for auth clients by ID
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3

  # ═══════════════════════════════════════════════════════════════
  # Payments — ЮKassa интеграция
  # ═══════════════════════════════════════════════════════════════
  # ⚠️ STUB: Using health function (d4e0rqplbonspm84pk3n) as placeholder
  # TODO: Replace with real heys-api-payments function ID after deployment
  # Deployment blocked: awaiting ЮKassa shopId + secretKey
  # ═══════════════════════════════════════════════════════════════
  /payments:
    get:
      summary: Payments healthcheck
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e0rqplbonspm84pk3n
    options:
      summary: CORS preflight for payments
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e0rqplbonspm84pk3n

  /payments/create:
    post:
      summary: Create ЮKassa payment
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e0rqplbonspm84pk3n
    options:
      summary: CORS preflight for payments create
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e0rqplbonspm84pk3n

  /payments/webhook:
    post:
      summary: ЮKassa webhook handler (payment notifications)
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e0rqplbonspm84pk3n
    options:
      summary: CORS preflight for payments webhook
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e0rqplbonspm84pk3n

  /payments/status:
    get:
      summary: Check payment status
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e0rqplbonspm84pk3n
    options:
      summary: CORS preflight for payments status
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e0rqplbonspm84pk3n

  # ═══════════════════════════════════════════════════════════════
  # Supabase-compatible routes (для совместимости)
  # ═══════════════════════════════════════════════════════════════

  # REST v1 — Supabase SDK format /rest/v1/table_name
  /rest/v1/{table}:
    get:
      summary: Supabase-compatible REST GET
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ea4j7eh05rtkjubipt
    post:
      summary: Supabase-compatible REST POST
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ea4j7eh05rtkjubipt
    patch:
      summary: Supabase-compatible REST PATCH
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ea4j7eh05rtkjubipt
    delete:
      summary: Supabase-compatible REST DELETE
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ea4j7eh05rtkjubipt
    options:
      summary: CORS preflight for REST v1
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ea4j7eh05rtkjubipt

  # Auth v1 — NEW: теперь редирект на реальную auth функцию
  /auth/v1/token:
    post:
      summary: Supabase-compatible token endpoint (redirect to login)
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3
    options:
      summary: CORS preflight for auth token
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3

  /auth/v1/user:
    get:
      summary: Supabase-compatible auth user check
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3
    options:
      summary: CORS preflight for auth user
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ef3c4o67vdg7o4c4d3
