# HEYS Project Workspace Configuration
packages:
  # Core packages
  - 'packages/*'
  - '!packages/analytics-dashboard' # Legacy, подлежит удалению

  # Applications
  - 'apps/web'
  # - 'apps/*' # Temporarily disabled other apps


  # Development tools
  - 'tools/*'

  # Documentation and legacy (not part of workspace)
  - '!docs/**'
  - '!temp/**'
  - '!TESTS/**'
  - '!старые МЕТОДОЛОГИИ И ИНСТРУКЦИИ ДЛЯ ИИ/**'
