// sections/index.ts — Экспорт всех секций
export { default as ComparisonSection } from './ComparisonSection'
export { default as CuratorSection } from './CuratorSection'
export { default as DemoSection } from './DemoSection'
export { default as HowItWorksSection } from './HowItWorksSection'
export { default as LifestyleSection } from './LifestyleSection'
export { default as NavigatorSection } from './NavigatorSection'
export { default as ObjectionsSection } from './ObjectionsSection'
export { default as PainSection } from './PainSection'
export { default as TrustSection } from './TrustSection'
